name: Update Distribution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
       verification: ${{ steps.verify.outcome }}

    steps:
      # Setup Project w/ composer
      - uses: actions/checkout@v3
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-source --ignore-platform-reqs"
          dependency-versions: "highest"

      # Verify Current Ref, returns 0 if Repository up to date
      - name: Verify current Ref
        id: verify
        run: php bin/console ispdb:verify
        continue-on-error: true

  update:
    needs: verify
    runs-on: ubuntu-latest
    # Only runs if Repository is outdated
    if: needs.verify.outputs.verification == 'failure'

    steps:
      - uses: actions/checkout@v3
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-source --ignore-platform-reqs"
          dependency-versions: "highest"
      - name: Update Distribution
        run: php bin/console ispdb:update

      - name: Publish Release
        uses: EndBug/add-and-commit@v9
        with:
          message: "fix(ci): Update Distribution"
