name: Update Distribution

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  verify:
    runs-on: ubuntu-20.04
    outputs: 
       verification: ${{ steps.verify.outcome }}  

    steps:
      # Setup Project w/ composer
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-source --ignore-platform-reqs"
          dependency-versions: "highest"  

      # Verify Current Ref, returns 0 if up to date
      - name: Verify current Ref
        id: verify
        run: php bin/console ispdb:verify
        continue-on-error: true
  
  update:
    needs: verify
    runs-on: ubuntu-20.04
    if: needs.verify.outputs.verification == 'failure'
    
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-source --ignore-platform-reqs"
          dependency-versions: "highest"
      - name: Update Distribution
        run: php bin/console ispdb:update
        
      - name: Add and Commit changes
      - uses: EndBug/add-and-commit@master
        with:
          message: Update Distribution
          push: false
        
      - id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_scheme: semantic
          version_type: patch
      
      - name: Push changes
        uses: "ad-m/github-push-action@master"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          tags: true
      
