name: Create Release

on: push

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.PAT }}
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            
            This is a Patch Release with no Breaking Changes.
          draft: false
          prerelease: false
